# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(through='content_api.Bookmark', to='content_api.Content'),
        ),
    ]
