# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('place', models.TextField(null=True)),
                ('realm_name', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('ticket_url', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('thumbnail', models.TextField(null=True)),
                ('gps_x', models.TextField(null=True)),
                ('gps_y', models.TextField(null=True)),
                ('place_url', models.TextField(null=True)),
                ('place_addr', models.TextField(null=True)),
                ('place_seq', models.TextField(null=True)),
                ('bookmarks', models.ManyToManyField(through='content_api.Bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Content')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='comment_user',
            field=models.ManyToManyField(related_name='comment_relate', through='content_api.ContentComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Content'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'content')]),
        ),
    ]
