# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('place', models.TextField(null=True)),
                ('realm_name', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('ticket_url', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('thumbnail', models.TextField(null=True)),
                ('gps_x', models.TextField(null=True)),
                ('gps_y', models.TextField(null=True)),
                ('place_url', models.TextField(null=True)),
                ('place_addr', models.TextField(null=True)),
                ('place_seq', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('score', models.CharField(max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
