# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='area',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='gps_x',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='gps_y',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='place_addr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='place_seq',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='place_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='realm_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='ticket_url',
            field=models.TextField(null=True),
        ),
    ]
