# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.ManyToManyField(through='content_api.PostComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
