# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0003_auto_20170414_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks_set', through='content_api.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
