# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0004_auto_20170414_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='bookmarks',
            field=models.ManyToManyField(through='content_api.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
