# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_api', '0005_auto_20170414_0605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'content')]),
        ),
    ]
